from flask import Blueprint, jsonify, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from datetime import datetime
from services.report_service import generate_monthly_report

from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet

import io

report_bp = Blueprint("reports", __name__)


# ===============================
# Monthly Report JSON (existing)
# ===============================
@report_bp.route("/monthly-report", methods=["GET"])
@jwt_required()
def monthly_report():

    user_id = int(get_jwt_identity())
    now = datetime.utcnow()

    report = generate_monthly_report(
        user_id,
        now.year,
        now.month
    )

    if report is None:
        return jsonify({"message": "No data for this month"}), 404

    return jsonify({
        "month": f"{now.year}-{now.month:02d}",
        "year": now.year,
        "report": report
    })


# ===============================
# Monthly Report PDF Download
# ===============================
@report_bp.route("/monthly-report/pdf", methods=["GET"])
@jwt_required()
def monthly_report_pdf():

    user_id = int(get_jwt_identity())
    now = datetime.utcnow()

    report = generate_monthly_report(
        user_id,
        now.year,
        now.month
    )

    if report is None:
        return jsonify({"message": "No data for this month"}), 404

    buffer = io.BytesIO()

    styles = getSampleStyleSheet()

    pdf = SimpleDocTemplate(buffer)

    content = []

    content.append(Paragraph("Diagnocare Monthly Health Report", styles["Title"]))
    content.append(Spacer(1, 20))

    content.append(Paragraph(f"Month: {now.year}-{now.month:02d}", styles["Normal"]))
    content.append(Paragraph(f"User ID: {user_id}", styles["Normal"]))
    content.append(Spacer(1, 20))

    content.append(Paragraph("Glucose Statistics", styles["Heading2"]))
    content.append(Spacer(1, 10))

    content.append(Paragraph(f"Total Entries: {report['entries']}", styles["Normal"]))
    content.append(Paragraph(f"Average Glucose: {report['average_glucose']} mg/dL", styles["Normal"]))
    content.append(Paragraph(f"Highest Glucose: {report['highest_glucose']} mg/dL", styles["Normal"]))
    content.append(Paragraph(f"Lowest Glucose: {report['lowest_glucose']} mg/dL", styles["Normal"]))
    content.append(Paragraph(f"Risk Trend: {report['risk_trend']}", styles["Normal"]))

    content.append(Spacer(1, 30))

    content.append(Paragraph("Generated by Diagnocare AI", styles["Italic"]))

    pdf.build(content)

    buffer.seek(0)

    return send_file(
        buffer,
        as_attachment=True,
        download_name=f"Diagnocare_Report_{now.year}_{now.month:02d}.pdf",
        mimetype="application/pdf"
    )